#!/bin/sh      
 ssh -tt arcsoftech@52.66.102.52 <<EOF
 send Arcsoftech@2894\r 
 cd /home/arcsoftech/BotFramework-Advil/jenkinsTest/jenkinsTest 
 git pull       
 npm install --production       
 pm2 restart www
 exit       
EOF

cd /home/arcsoftech/BotFramework-Advil/jenkinsTest/jenkinsTest 
echo "Arcsoftech@2894" | sudo -S git pull
echo "Arcsoftech@2894" | sudo -S npm install 
echo "Arcsoftech@2894" | sudo -S pm2 restart www